# Generated by Django 5.0.6 on 2024-07-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acc_number',
            field=models.IntegerField(default=4518101),
        ),
        migrations.AddField(
            model_name='user',
            name='acc_status',
            field=models.BooleanField(default=False),
        ),
    ]
